// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://nysssmzlyqrdnweufrbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55c3NzbXpseXFyZG53ZXVmcmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDI0MDgsImV4cCI6MjA2ODk3ODQwOH0.hsb_FRBM5PWrTbuFg-p4AQxEUu2Kjq2CSBrcntYd-MU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
